name: Build

on:
  push:
    branches: [ dev, main, release/1.x ]
    paths-ignore:
    - 'doc/**'
    - '*.md'

  pull_request:
    branches: [ dev, main, release/1.x ]
    paths-ignore:
    - 'doc/**'
    - '*.md'

jobs:

  build:
    runs-on: windows-latest
    env:
        DOTNET_NOLOGO: true
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Setup dotnet 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.*

    - name: Generate build number
      shell: powershell
      run: |
        echo "GH_RUN_NUMBER = $GITHUB_RUN_NUMBER"
        echo "nugetVersion=$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

    - name: Pack
      shell: powershell
      run: |
        Start-FileDownload 'https://dist.nuget.org/win-x86-commandline/latest/nuget.exe'
        .\pack.ps1
